version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: AfterInstallHook.sh
      timeout: 300
